/**********************************************************************
 * Extern for createAuth0Client
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var createAuth0Client = {
  "Auth0Client": function () {},
  "AuthenticationError": {
    "fromPayload": function () {},
    "stackTraceLimit": {}
  },
  "GenericError": {
    "fromPayload": function () {},
    "stackTraceLimit": {}
  },
  "PopupTimeoutError": {
    "fromPayload": function () {},
    "stackTraceLimit": {}
  },
  "TimeoutError": {
    "fromPayload": function () {},
    "stackTraceLimit": {}
  },
  "createAuth0Client": {
    "Auth0Client": function () {},
    "AuthenticationError": {
      "fromPayload": function () {},
      "stackTraceLimit": {}
    },
    "GenericError": {
      "fromPayload": function () {},
      "stackTraceLimit": {}
    },
    "PopupTimeoutError": {
      "fromPayload": function () {},
      "stackTraceLimit": {}
    },
    "TimeoutError": {
      "fromPayload": function () {},
      "stackTraceLimit": {}
    },
    "createAuth0Client": function () {}
  }
};
createAuth0Client.Auth0Client.prototype = {
  "_authorizeUrl": function () {},
  "_getParams": function () {},
  "_getTokenFromIFrame": function () {},
  "_getTokenSilently": function () {},
  "_getTokenUsingRefreshToken": function () {},
  "_parseNumber": function () {},
  "_url": function () {},
  "_verifyIdToken": function () {},
  "buildAuthorizeUrl": function () {},
  "buildLogoutUrl": function () {},
  "checkSession": function () {},
  "getIdTokenClaims": function () {},
  "getTokenSilently": function () {},
  "getTokenWithPopup": function () {},
  "getUser": function () {},
  "handleRedirectCallback": function () {},
  "isAuthenticated": function () {},
  "loginWithPopup": function () {},
  "loginWithRedirect": function () {},
  "logout": function () {}
};
createAuth0Client.AuthenticationError.prototype = {
  "constructor": function () {}
};
createAuth0Client.GenericError.prototype = {
  "constructor": function () {}
};
createAuth0Client.PopupTimeoutError.prototype = {
  "constructor": function () {}
};
createAuth0Client.TimeoutError.prototype = {
  "constructor": function () {}
};
createAuth0Client.createAuth0Client.Auth0Client.prototype = {
  "_authorizeUrl": function () {},
  "_getParams": function () {},
  "_getTokenFromIFrame": function () {},
  "_getTokenSilently": function () {},
  "_getTokenUsingRefreshToken": function () {},
  "_parseNumber": function () {},
  "_url": function () {},
  "_verifyIdToken": function () {},
  "buildAuthorizeUrl": function () {},
  "buildLogoutUrl": function () {},
  "checkSession": function () {},
  "getIdTokenClaims": function () {},
  "getTokenSilently": function () {},
  "getTokenWithPopup": function () {},
  "getUser": function () {},
  "handleRedirectCallback": function () {},
  "isAuthenticated": function () {},
  "loginWithPopup": function () {},
  "loginWithRedirect": function () {},
  "logout": function () {}
};
createAuth0Client.createAuth0Client.AuthenticationError.prototype = {
  "constructor": function () {}
};
createAuth0Client.createAuth0Client.GenericError.prototype = {
  "constructor": function () {}
};
createAuth0Client.createAuth0Client.PopupTimeoutError.prototype = {
  "constructor": function () {}
};
createAuth0Client.createAuth0Client.TimeoutError.prototype = {
  "constructor": function () {}
};
/**********************************************************************
 * End Generated Extern for createAuth0Client
/**********************************************************************/
